# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='dateModified',
            new_name='date_modified',
        ),
    ]
